version: "3.3"

services:
  app:
    build: .
    command: python main.py
    volumes:
      - .:/parsing/
    ports:
      - "8000:8000"
    environment:
      FASTAPI_SERVICE_CONTAINER_HOST: 0.0.0.0
      FASTAPI_SERVICE_CONTAINER_PORT: 8000
      FASTAPI_SERVICE_MONGO_HOST: mongodb
      FASTAPI_SERVICE_MONGO_PORT: 27017
      FASTAPI_SERVICE_MONGO_USERNAME: mongoadmin
      FASTAPI_SERVICE_MONGO_PASSWORD: mongopassword
    depends_on:
      - mongodb


  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
